name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-npm
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            ${{ env.cache-name }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: npm run lint
        continue-on-error: true
      - name: Test
        run: npm run test
